const { Schema } = require('mongoose');

const blogSchema = new Schema({
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        required: true
    },
    post: {
        type: String,
        required: true
    }, //HTML String (generated by Quill),
    author: {
        type: Schema.Types.ObjectId,
        ref: "user",
        required: true
    }
}, { collection: "blog", timestamps: true });

module.exports = blogSchema;